syntax = "proto3";

package infralenta.storage.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/askerdev/bitstar/proto/infralenta/storage/v1;storagepb";

service EventService {
  rpc BatchCreateEvents(BatchCreateEventsRequest) returns (BatchCreateEventsResponse);

  rpc ListEvents(ListEventsRequest) returns (ListEventsResponse);
}

message Event {
  string id = 1;

  string title = 2;

  string description = 3;

  Resource resource = 4;

  google.protobuf.Timestamp start_time = 5;

  google.protobuf.Timestamp end_time = 6;

  repeated string tags = 7;

  map<string, string> annotations = 8;

  string created_by = 9;

  string updated_by = 10;

  google.protobuf.Timestamp create_time = 11;

  google.protobuf.Timestamp update_time = 12;

  google.protobuf.Timestamp delete_time = 13;
}

message Resource {
  string type_code = 1;
  string external_id = 2;
}

message EventKey {
  Resource resource = 1;
  google.protobuf.Timestamp start_time = 2;
  string id = 3;
}

message CreateEventRequest {
  Event event = 1;
}

message BatchCreateEventsRequest {
  repeated CreateEventRequest requests = 1;
}

message BatchCreateEventsResponse {
  repeated Event events = 1;
}

message ListEventsRequest {
  int32 page_size = 1;

  string page_token = 2;

  google.protobuf.Timestamp start_time = 3;

  google.protobuf.Timestamp end_time = 4;

  string filter = 5;
}

message ListEventsResponse {
  repeated Event events = 1;

  string next_page_token = 2;

  Stats stats = 3;
}

message Stats {
  int32 current_mem_table_size = 1;
  int32 pending_index_count = 2;
  map<int32, int32> pending_index_cardinalities = 3;
  map<int32, int32> level_cardinalities = 4;
}
