// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event_service.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Resource      *Resource              `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	DeleteTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Event) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Event) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Event) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Event) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Event) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeCode      string                 `protobuf:"bytes,1,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_event_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type EventKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventKey) Reset() {
	*x = EventKey{}
	mi := &file_event_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventKey) ProtoMessage() {}

func (x *EventKey) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventKey.ProtoReflect.Descriptor instead.
func (*EventKey) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{2}
}

func (x *EventKey) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EventKey) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *EventKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type BatchCreateEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateEventRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateEventsRequest) Reset() {
	*x = BatchCreateEventsRequest{}
	mi := &file_event_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsRequest) ProtoMessage() {}

func (x *BatchCreateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateEventsRequest) GetRequests() []*CreateEventRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateEventsResponse) Reset() {
	*x = BatchCreateEventsResponse{}
	mi := &file_event_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsResponse) ProtoMessage() {}

func (x *BatchCreateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCreateEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Filter        string                 `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Stats         *Stats                 `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEventsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Stats struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CurrentMemTableSize       int32                  `protobuf:"varint,1,opt,name=current_mem_table_size,json=currentMemTableSize,proto3" json:"current_mem_table_size,omitempty"`
	PendingIndexCount         int32                  `protobuf:"varint,2,opt,name=pending_index_count,json=pendingIndexCount,proto3" json:"pending_index_count,omitempty"`
	PendingIndexCardinalities map[int32]int32        `protobuf:"bytes,3,rep,name=pending_index_cardinalities,json=pendingIndexCardinalities,proto3" json:"pending_index_cardinalities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LevelCardinalities        map[int32]int32        `protobuf:"bytes,4,rep,name=level_cardinalities,json=levelCardinalities,proto3" json:"level_cardinalities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_event_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{8}
}

func (x *Stats) GetCurrentMemTableSize() int32 {
	if x != nil {
		return x.CurrentMemTableSize
	}
	return 0
}

func (x *Stats) GetPendingIndexCount() int32 {
	if x != nil {
		return x.PendingIndexCount
	}
	return 0
}

func (x *Stats) GetPendingIndexCardinalities() map[int32]int32 {
	if x != nil {
		return x.PendingIndexCardinalities
	}
	return nil
}

func (x *Stats) GetLevelCardinalities() map[int32]int32 {
	if x != nil {
		return x.LevelCardinalities
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UpdateEventRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_event_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{10}
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_service_proto_rawDescGZIP(), []int{12}
}

var File_event_service_proto protoreflect.FileDescriptor

const file_event_service_proto_rawDesc = "" +
	"\n" +
	"\x13event_service.proto\x12\x15infralenta.storage.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x05\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\bresource\x18\x04 \x01(\v2\x1f.infralenta.storage.v1.ResourceR\bresource\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12O\n" +
	"\vannotations\x18\b \x03(\v2-.infralenta.storage.v1.Event.AnnotationsEntryR\vannotations\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12;\n" +
	"\vdelete_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleteTime\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\bResource\x12\x1b\n" +
	"\ttype_code\x18\x01 \x01(\tR\btypeCode\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"\x92\x01\n" +
	"\bEventKey\x12;\n" +
	"\bresource\x18\x01 \x01(\v2\x1f.infralenta.storage.v1.ResourceR\bresource\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"H\n" +
	"\x12CreateEventRequest\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.infralenta.storage.v1.EventR\x05event\"a\n" +
	"\x18BatchCreateEventsRequest\x12E\n" +
	"\brequests\x18\x01 \x03(\v2).infralenta.storage.v1.CreateEventRequestR\brequests\"Q\n" +
	"\x19BatchCreateEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.infralenta.storage.v1.EventR\x06events\"\xd9\x01\n" +
	"\x11ListEventsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\"\xa6\x01\n" +
	"\x12ListEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.infralenta.storage.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x122\n" +
	"\x05stats\x18\x03 \x01(\v2\x1c.infralenta.storage.v1.StatsR\x05stats\"\xe5\x03\n" +
	"\x05Stats\x123\n" +
	"\x16current_mem_table_size\x18\x01 \x01(\x05R\x13currentMemTableSize\x12.\n" +
	"\x13pending_index_count\x18\x02 \x01(\x05R\x11pendingIndexCount\x12{\n" +
	"\x1bpending_index_cardinalities\x18\x03 \x03(\v2;.infralenta.storage.v1.Stats.PendingIndexCardinalitiesEntryR\x19pendingIndexCardinalities\x12e\n" +
	"\x13level_cardinalities\x18\x04 \x03(\v24.infralenta.storage.v1.Stats.LevelCardinalitiesEntryR\x12levelCardinalities\x1aL\n" +
	"\x1ePendingIndexCardinalitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aE\n" +
	"\x17LevelCardinalitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x85\x01\n" +
	"\x12UpdateEventRequest\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.infralenta.storage.v1.EventR\x05event\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x15\n" +
	"\x13UpdateEventResponse\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEventResponse2\xb5\x03\n" +
	"\fEventService\x12v\n" +
	"\x11BatchCreateEvents\x12/.infralenta.storage.v1.BatchCreateEventsRequest\x1a0.infralenta.storage.v1.BatchCreateEventsResponse\x12a\n" +
	"\n" +
	"ListEvents\x12(.infralenta.storage.v1.ListEventsRequest\x1a).infralenta.storage.v1.ListEventsResponse\x12d\n" +
	"\vUpdateEvent\x12).infralenta.storage.v1.UpdateEventRequest\x1a*.infralenta.storage.v1.UpdateEventResponse\x12d\n" +
	"\vDeleteEvent\x12).infralenta.storage.v1.DeleteEventRequest\x1a*.infralenta.storage.v1.DeleteEventResponseBCZAgithub.com/askerdev/bitstar/proto/infralenta/storage/v1;storagepbb\x06proto3"

var (
	file_event_service_proto_rawDescOnce sync.Once
	file_event_service_proto_rawDescData []byte
)

func file_event_service_proto_rawDescGZIP() []byte {
	file_event_service_proto_rawDescOnce.Do(func() {
		file_event_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_service_proto_rawDesc), len(file_event_service_proto_rawDesc)))
	})
	return file_event_service_proto_rawDescData
}

var file_event_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_event_service_proto_goTypes = []any{
	(*Event)(nil),                     // 0: infralenta.storage.v1.Event
	(*Resource)(nil),                  // 1: infralenta.storage.v1.Resource
	(*EventKey)(nil),                  // 2: infralenta.storage.v1.EventKey
	(*CreateEventRequest)(nil),        // 3: infralenta.storage.v1.CreateEventRequest
	(*BatchCreateEventsRequest)(nil),  // 4: infralenta.storage.v1.BatchCreateEventsRequest
	(*BatchCreateEventsResponse)(nil), // 5: infralenta.storage.v1.BatchCreateEventsResponse
	(*ListEventsRequest)(nil),         // 6: infralenta.storage.v1.ListEventsRequest
	(*ListEventsResponse)(nil),        // 7: infralenta.storage.v1.ListEventsResponse
	(*Stats)(nil),                     // 8: infralenta.storage.v1.Stats
	(*UpdateEventRequest)(nil),        // 9: infralenta.storage.v1.UpdateEventRequest
	(*UpdateEventResponse)(nil),       // 10: infralenta.storage.v1.UpdateEventResponse
	(*DeleteEventRequest)(nil),        // 11: infralenta.storage.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),       // 12: infralenta.storage.v1.DeleteEventResponse
	nil,                               // 13: infralenta.storage.v1.Event.AnnotationsEntry
	nil,                               // 14: infralenta.storage.v1.Stats.PendingIndexCardinalitiesEntry
	nil,                               // 15: infralenta.storage.v1.Stats.LevelCardinalitiesEntry
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 17: google.protobuf.FieldMask
}
var file_event_service_proto_depIdxs = []int32{
	1,  // 0: infralenta.storage.v1.Event.resource:type_name -> infralenta.storage.v1.Resource
	16, // 1: infralenta.storage.v1.Event.start_time:type_name -> google.protobuf.Timestamp
	16, // 2: infralenta.storage.v1.Event.end_time:type_name -> google.protobuf.Timestamp
	13, // 3: infralenta.storage.v1.Event.annotations:type_name -> infralenta.storage.v1.Event.AnnotationsEntry
	16, // 4: infralenta.storage.v1.Event.create_time:type_name -> google.protobuf.Timestamp
	16, // 5: infralenta.storage.v1.Event.update_time:type_name -> google.protobuf.Timestamp
	16, // 6: infralenta.storage.v1.Event.delete_time:type_name -> google.protobuf.Timestamp
	1,  // 7: infralenta.storage.v1.EventKey.resource:type_name -> infralenta.storage.v1.Resource
	16, // 8: infralenta.storage.v1.EventKey.start_time:type_name -> google.protobuf.Timestamp
	0,  // 9: infralenta.storage.v1.CreateEventRequest.event:type_name -> infralenta.storage.v1.Event
	3,  // 10: infralenta.storage.v1.BatchCreateEventsRequest.requests:type_name -> infralenta.storage.v1.CreateEventRequest
	0,  // 11: infralenta.storage.v1.BatchCreateEventsResponse.events:type_name -> infralenta.storage.v1.Event
	16, // 12: infralenta.storage.v1.ListEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	16, // 13: infralenta.storage.v1.ListEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 14: infralenta.storage.v1.ListEventsResponse.events:type_name -> infralenta.storage.v1.Event
	8,  // 15: infralenta.storage.v1.ListEventsResponse.stats:type_name -> infralenta.storage.v1.Stats
	14, // 16: infralenta.storage.v1.Stats.pending_index_cardinalities:type_name -> infralenta.storage.v1.Stats.PendingIndexCardinalitiesEntry
	15, // 17: infralenta.storage.v1.Stats.level_cardinalities:type_name -> infralenta.storage.v1.Stats.LevelCardinalitiesEntry
	0,  // 18: infralenta.storage.v1.UpdateEventRequest.event:type_name -> infralenta.storage.v1.Event
	17, // 19: infralenta.storage.v1.UpdateEventRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 20: infralenta.storage.v1.EventService.BatchCreateEvents:input_type -> infralenta.storage.v1.BatchCreateEventsRequest
	6,  // 21: infralenta.storage.v1.EventService.ListEvents:input_type -> infralenta.storage.v1.ListEventsRequest
	9,  // 22: infralenta.storage.v1.EventService.UpdateEvent:input_type -> infralenta.storage.v1.UpdateEventRequest
	11, // 23: infralenta.storage.v1.EventService.DeleteEvent:input_type -> infralenta.storage.v1.DeleteEventRequest
	5,  // 24: infralenta.storage.v1.EventService.BatchCreateEvents:output_type -> infralenta.storage.v1.BatchCreateEventsResponse
	7,  // 25: infralenta.storage.v1.EventService.ListEvents:output_type -> infralenta.storage.v1.ListEventsResponse
	10, // 26: infralenta.storage.v1.EventService.UpdateEvent:output_type -> infralenta.storage.v1.UpdateEventResponse
	12, // 27: infralenta.storage.v1.EventService.DeleteEvent:output_type -> infralenta.storage.v1.DeleteEventResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_event_service_proto_init() }
func file_event_service_proto_init() {
	if File_event_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_service_proto_rawDesc), len(file_event_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_service_proto_goTypes,
		DependencyIndexes: file_event_service_proto_depIdxs,
		MessageInfos:      file_event_service_proto_msgTypes,
	}.Build()
	File_event_service_proto = out.File
	file_event_service_proto_goTypes = nil
	file_event_service_proto_depIdxs = nil
}
